-----------------------------------
-- Setup HOT tables
-----------------------------------
CREATE TABLE PAYMENTINTERCHANGE
(	 
     PAYMENTINTERCHANGEKEY   NUMBER(38,0) NOT NULL,
     INCOMING                CHAR(1) NOT NULL,
     DISPLAYINTERCHANGEID    VARCHAR2(128) NOT NULL,
     FILENAME                VARCHAR2(256),
     FILEFORMAT              VARCHAR2(128),
     TRANSPORTTIME           DATE,
     STATUS                  VARCHAR2(30),
     TRANSPORTDATA           BLOB DEFAULT EMPTY_BLOB(),
     DETAILS                 XMLTYPE,
     PROCESSINGDETAILS       XMLTYPE,
     BANKGROUPID             VARCHAR2(30) NOT NULL,
     CUSTOMERPAYMENTTYPEKEY  NUMBER(38,0),
     CLEARINGCONDITIONKEY    NUMBER(38,0) NOT NULL,
     BANKPAYMENTTYPEKEY      NUMBER(38,0),
     BANKINGENTITYKEY        NUMBER(38,0),
     ILMKEY                 TIMESTAMP default TO_TIMESTAMP('10-DEC-2015:10:10:10','DD-MON-YYYY:HH24:MI:SS'),
     VERSION                NUMBER(38,0) NOT NULL ENABLE,
     WHENMODIFIED            DATE NOT NULL ENABLE,
     CONSTRAINT "PK_PAYMENTINTERCHANGE" PRIMARY KEY ("PAYMENTINTERCHANGEKEY"))
XMLTYPE COLUMN DETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_HOT_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
XMLTYPE COLUMN PROCESSINGDETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_HOT_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
TABLESPACE ILM_HOT_TBS
PARTITION BY RANGE (ILMKEY) 
SUBPARTITION BY HASH(PAYMENTINTERCHANGEKEY) SUBPARTITIONS 16
(
    PARTITION P2015_11 VALUES LESS THAN (TO_DATE('2015-12-01', 'yyyy-MM-dd')),
    PARTITION P2015_12 VALUES LESS THAN (TO_DATE('2016-01-01', 'yyyy-MM-dd')),
    PARTITION P2016_01 VALUES LESS THAN (TO_DATE('2016-02-01', 'yyyy-MM-dd')),
    PARTITION P9999_12 VALUES LESS THAN (MAXVALUE)
);

-- add index
CREATE INDEX "I_INTCH_TRANSPORTDATE" ON "PAYMENTINTERCHANGE" ("TRANSPORTTIME") 
TABLESPACE "ILM_HOT_TBS";

CREATE INDEX "I_PMT_INTERCHANGE_FILENAME" ON "PAYMENTINTERCHANGE" ("FILENAME") 
TABLESPACE "ILM_HOT_TBS";

CREATE INDEX "I_PMT_INTERCHANGE_STATUS" ON "PAYMENTINTERCHANGE" ("STATUS") LOCAL
TABLESPACE "ILM_HOT_TBS";

-- allow row movement
ALTER TABLE PAYMENTINTERCHANGE ENABLE ROW MOVEMENT;

-- Insert paymentInterchange
Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (1530106,'T','OPF1530106','pacs.002 Interchange.xml','pacs.002.001.06',to_date('10-DEC-15 17:21:29','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T13:24:25Z</IntchngDtTm><IntchngRef>PACS.002-MIX-5</IntchngRef><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_RBS</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5014,null,-5002,2,to_date('10-DEC-15 17:21:29','DD-MON-RR HH24:MI:SS'));
Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (1630101,'F','OPF1630101','AcctEvt-BlueBank-DaDiOPF1630101.xml','pacs.008.001.04',to_date('15-DEC-15 14:09:39','DD-MON-RR HH24:MI:SS'),'Rejected','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-15T13:09:18Z</IntchngDtTm><IntchngRef>OPF1630101</IntchngRef><Mur>OPF1630101</Mur><NbOfTrns>1</NbOfTrns><RcvgPty>RBOSGB2LXXX</RcvgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Sbm><InitRunId>17301000</InitRunId></Sbm></Intchng>','OPFBankgroup',null,-5014,null,-5002,6,to_date('15-DEC-15 14:19:04','DD-MON-RR HH24:MI:SS'));
Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (1630102,'T','OPF1630102','pacs.002 Interchange.xml','pacs.002.001.06',to_date('15-DEC-15 14:14:47','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-15T13:24:25Z</IntchngDtTm><IntchngRef>PACS.002-MIX-5</IntchngRef><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_RBS</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5014,null,-5002,2,to_date('15-DEC-15 14:14:47','DD-MON-RR HH24:MI:SS'));
Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (1530107,'T','OPF1530107','pain.001-2TXN.xml','pain.001.001.05',to_date('10-DEC-15 17:45:50','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T07:27:10Z</IntchngDtTm><IntchngRef>ORGINTCHG-034</IntchngRef><NbOfTrns>2</NbOfTrns><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_CUST</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5004,null,-5002,2,to_date('10-DEC-15 17:45:50','DD-MON-RR HH24:MI:SS'));
Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (1530108,'F','OPF1530108','AcctEvt-BlueBank-DaDiOPF1530108.xml','pacs.008.001.04',to_date('10-DEC-15 17:45:51','DD-MON-RR HH24:MI:SS'),'Rejected','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T16:45:51Z</IntchngDtTm><IntchngRef>OPF1530108</IntchngRef><Mur>OPF1530108</Mur><NbOfTrns>1</NbOfTrns><RcvgPty>RBOSGB2LXXX</RcvgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Sbm><InitRunId>16801002</InitRunId></Sbm></Intchng>','OPFBankgroup',null,-5014,null,-5002,6,to_date('10-DEC-15 18:06:18','DD-MON-RR HH24:MI:SS'));
Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (1530109,'T','OPF1530109','pacs.002 Interchange.xml','pacs.002.001.06',to_date('10-DEC-15 17:46:32','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T13:24:25Z</IntchngDtTm><IntchngRef>PACS.002-MIX-5</IntchngRef><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_RBS</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5014,null,-5002,2,to_date('10-DEC-15 17:46:32','DD-MON-RR HH24:MI:SS'));
Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (1530104,'T','OPF1530104','pain.001-2TXN.xml','pain.001.001.05',to_date('10-DEC-15 17:19:21','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T07:27:10Z</IntchngDtTm><IntchngRef>ORGINTCHG-033</IntchngRef><NbOfTrns>2</NbOfTrns><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_CUST</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5004,null,-5002,2,to_date('10-DEC-15 17:19:21','DD-MON-RR HH24:MI:SS'));
Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (1530105,'F','OPF1530105','AcctEvt-BlueBank-DaDiOPF1530105.xml','pacs.008.001.04',to_date('10-DEC-15 17:19:23','DD-MON-RR HH24:MI:SS'),'Rejected','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T16:19:22Z</IntchngDtTm><IntchngRef>OPF1530105</IntchngRef><Mur>OPF1530105</Mur><NbOfTrns>1</NbOfTrns><RcvgPty>RBOSGB2LXXX</RcvgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Sbm><InitRunId>16801001</InitRunId></Sbm></Intchng>','OPFBankgroup',null,-5014,null,-5002,6,to_date('10-DEC-15 17:34:56','DD-MON-RR HH24:MI:SS'));
Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (1530103,'T','OPF1530103','pacs.002 Interchange.xml','pacs.002.001.06',to_date('10-DEC-15 16:03:13','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T13:24:25Z</IntchngDtTm><IntchngRef>PACS.002-MIX-5</IntchngRef><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_RBS</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5014,null,-5002,2,to_date('10-DEC-15 16:03:13','DD-MON-RR HH24:MI:SS'));
Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (1680100,'T','OPF1680100','pain.001-2TXN.xml','pain.001.001.05',to_date('15-DEC-15 16:29:36','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-15T07:27:10Z</IntchngDtTm><IntchngRef>ORGINTCHG-038</IntchngRef><NbOfTrns>2</NbOfTrns><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_CUST</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5004,null,-5002,2,to_date('15-DEC-15 16:29:36','DD-MON-RR HH24:MI:SS'));
Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (1630002,'T','OPF1630002','pacs.002 Interchange.xml','pacs.002.001.06',to_date('11-DEC-15 17:09:24','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T13:24:25Z</IntchngDtTm><IntchngRef>PACS.002-MIX-5</IntchngRef><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_RBS</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5014,null,-5002,2,to_date('11-DEC-15 17:09:24','DD-MON-RR HH24:MI:SS'));
Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (1430006,'T','OPF1430006','pacs.002 Interchange.xml','pacs.002.001.06',to_date('09-DEC-15 16:53:42','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-09T13:24:25Z</IntchngDtTm><IntchngRef>PACS.002-MIX-5</IntchngRef><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_RBS</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5014,null,-5002,2,to_date('09-DEC-15 16:53:42','DD-MON-RR HH24:MI:SS'));
Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (1530000,'T','OPF1530000','pain.001-2TXN.xml','pain.001.001.05',to_date('10-DEC-15 15:29:58','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T07:27:10Z</IntchngDtTm><IntchngRef>ORGINTCHG-030</IntchngRef><NbOfTrns>2</NbOfTrns><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_CUST</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5004,null,-5002,2,to_date('10-DEC-15 15:29:59','DD-MON-RR HH24:MI:SS'));
Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (1530102,'T','OPF1530102','pain.001-2TXN.xml','pain.001.001.05',to_date('10-DEC-15 15:50:24','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T07:27:10Z</IntchngDtTm><IntchngRef>ORGINTCHG-031</IntchngRef><NbOfTrns>2</NbOfTrns><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_CUST</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5004,null,-5002,2,to_date('10-DEC-15 15:50:24','DD-MON-RR HH24:MI:SS'));
Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (1630100,'T','OPF1630100','pain.001-2TXN.xml','pain.001.001.05',to_date('15-DEC-15 14:00:26','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-15T07:27:10Z</IntchngDtTm><IntchngRef>ORGINTCHG-037</IntchngRef><NbOfTrns>2</NbOfTrns><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_CUST</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5004,null,-5002,2,to_date('15-DEC-15 14:00:27','DD-MON-RR HH24:MI:SS'));
Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (1680101,'F','OPF1680101','AcctEvt-BlueBank-DaDiOPF1680101.xml','pacs.008.001.04',to_date('15-DEC-15 16:29:40','DD-MON-RR HH24:MI:SS'),'Processed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-15T15:29:40Z</IntchngDtTm><IntchngRef>OPF1680101</IntchngRef><Mur>OPF1680101</Mur><NbOfTrns>1</NbOfTrns><RcvgPty>RBOSGB2LXXX</RcvgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Sbm><InitRunId>17801000</InitRunId></Sbm></Intchng>','OPFBankgroup',null,-5014,null,-5002,5,to_date('15-DEC-15 16:29:40','DD-MON-RR HH24:MI:SS'));

DECLARE
  pid NUMBER := 1000100;
BEGIN
  FOR i IN 1..300
  LOOP
    pid := pid + 1;
    Insert into PAYMENTINTERCHANGE (PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) values (pid,'F','OPF1680101','AcctEvt-BlueBank-DaDiOPF1680101.xml','pacs.008.001.04',to_date('15-DEC-15 16:29:40','DD-MON-RR HH24:MI:SS'),'Processed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-15T15:29:40Z</IntchngDtTm><IntchngRef>OPF1680101</IntchngRef><Mur>OPF1680101</Mur><NbOfTrns>1</NbOfTrns><RcvgPty>RBOSGB2LXXX</RcvgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Sbm><InitRunId>17801000</InitRunId></Sbm></Intchng>','OPFBankgroup',null,-5014,null,-5002,5,to_date('15-DEC-15 16:29:40','DD-MON-RR HH24:MI:SS'));
  END LOOP;
END;
/

update PAYMENTINTERCHANGE set ILMKEY = add_months(ILMKEY,-1) where PAYMENTINTERCHANGEKEY <= 1530102;
update PAYMENTINTERCHANGE set ILMKEY = add_months(ILMKEY,1) where PAYMENTINTERCHANGEKEY >= 1530109;
commit;

-----------------------------------
-- Setup COLD tables
-----------------------------------
CREATE TABLE PAYMENTINTERCHANGECOLD
(	 
     PAYMENTINTERCHANGEKEY   NUMBER(38,0) NOT NULL,
     INCOMING                CHAR(1) NOT NULL,
     DISPLAYINTERCHANGEID    VARCHAR2(128) NOT NULL,
     FILENAME                VARCHAR2(256),
     FILEFORMAT              VARCHAR2(128),
     TRANSPORTTIME           DATE,
     STATUS                  VARCHAR2(30),
     TRANSPORTDATA           BLOB DEFAULT EMPTY_BLOB(),
     DETAILS                 XMLTYPE,
     PROCESSINGDETAILS       XMLTYPE,
     BANKGROUPID             VARCHAR2(30) NOT NULL,
     CUSTOMERPAYMENTTYPEKEY  NUMBER(38,0),
     CLEARINGCONDITIONKEY    NUMBER(38,0) NOT NULL,
     BANKPAYMENTTYPEKEY      NUMBER(38,0),
     BANKINGENTITYKEY        NUMBER(38,0),
     ILMKEY                 TIMESTAMP default TO_TIMESTAMP('10-DEC-2015:10:10:10','DD-MON-YYYY:HH24:MI:SS'),
     VERSION                NUMBER(38,0) NOT NULL ENABLE,
     WHENMODIFIED            DATE NOT NULL ENABLE,
     CONSTRAINT "PK_PAYMENTINTERCHANGECOLD" PRIMARY KEY ("PAYMENTINTERCHANGEKEY"))
XMLTYPE COLUMN DETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_COLD_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
XMLTYPE COLUMN PROCESSINGDETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_COLD_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
TABLESPACE ILM_COLD_TBS
PARTITION BY RANGE (ILMKEY) 
SUBPARTITION BY HASH(PAYMENTINTERCHANGEKEY) SUBPARTITIONS 16
(
    PARTITION P2015_10 VALUES LESS THAN (TO_DATE('2015-11-01', 'yyyy-MM-dd')),
    PARTITION P9999_12 VALUES LESS THAN (MAXVALUE)
);

-- add index
CREATE INDEX "I_INTCHC_TRANSPORTDATE" ON "PAYMENTINTERCHANGECOLD" ("TRANSPORTTIME") 
TABLESPACE "ILM_COLD_TBS";

CREATE INDEX "I_PMT_INTERCHANGEC_FILENAME" ON "PAYMENTINTERCHANGECOLD" ("FILENAME") 
TABLESPACE "ILM_COLD_TBS";

CREATE INDEX "I_PMT_INTERCHANGEC_STATUS" ON "PAYMENTINTERCHANGECOLD" ("STATUS") LOCAL
TABLESPACE "ILM_COLD_TBS";


-----------------------------------
-- Setup TEMP tables
-----------------------------------
-- create temp table
CREATE TABLE PAYMENTINTERCHANGETEMP
(	 
     PAYMENTINTERCHANGEKEY   NUMBER(38,0) NOT NULL,
     INCOMING                CHAR(1) NOT NULL,
     DISPLAYINTERCHANGEID    VARCHAR2(128) NOT NULL,
     FILENAME                VARCHAR2(256),
     FILEFORMAT              VARCHAR2(128),
     TRANSPORTTIME           DATE,
     STATUS                  VARCHAR2(30),
     TRANSPORTDATA           BLOB DEFAULT EMPTY_BLOB(),
     DETAILS                 XMLTYPE,
     PROCESSINGDETAILS       XMLTYPE,
     BANKGROUPID             VARCHAR2(30) NOT NULL,
     CUSTOMERPAYMENTTYPEKEY  NUMBER(38,0),
     CLEARINGCONDITIONKEY    NUMBER(38,0) NOT NULL,
     BANKPAYMENTTYPEKEY      NUMBER(38,0),
     BANKINGENTITYKEY        NUMBER(38,0),
     ILMKEY                 TIMESTAMP default TO_TIMESTAMP('10-DEC-2015:10:10:10','DD-MON-YYYY:HH24:MI:SS'),
     VERSION                NUMBER(38,0) NOT NULL ENABLE,
     WHENMODIFIED            DATE NOT NULL ENABLE,
     CONSTRAINT "PK_PAYMENTINTERCHANGETEMP" PRIMARY KEY ("PAYMENTINTERCHANGEKEY"))
XMLTYPE COLUMN DETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_COLD_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
XMLTYPE COLUMN PROCESSINGDETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_COLD_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
TABLESPACE ILM_COLD_TBS
PARTITION BY HASH(PAYMENTINTERCHANGEKEY) PARTITIONS 16;

-----------------------------------
-- ILM tables population
-----------------------------------
INSERT INTO ILMCONFIG (ID, PARAM, VALUE, LASTMODIFIED) VALUES (ILMCONFIG_SEQUENCE.nextval, 'HOT_TABLESPACE_NAME', 'ILM_HOT_TBS', SYSTIMESTAMP);
INSERT INTO ILMCONFIG (ID, PARAM, VALUE, LASTMODIFIED) VALUES (ILMCONFIG_SEQUENCE.nextval, 'WARM_TABLESPACE_NAME', 'ILM_WARM_TBS', SYSTIMESTAMP);
INSERT INTO ILMCONFIG (ID, PARAM, VALUE, LASTMODIFIED) VALUES (ILMCONFIG_SEQUENCE.nextval, 'COLD_TABLESPACE_NAME', 'ILM_COLD_TBS', SYSTIMESTAMP);
INSERT INTO ILMCONFIG (ID, PARAM, VALUE, LASTMODIFIED) VALUES (ILMCONFIG_SEQUENCE.nextval, 'DORMANT_TABLESPACE_NAME', 'ILM_DORMANT_TBS', SYSTIMESTAMP);
INSERT INTO ILMCONFIG (ID, PARAM, VALUE, LASTMODIFIED) VALUES (ILMCONFIG_SEQUENCE.nextval, 'PARALLEL_DEGREE', '4', SYSTIMESTAMP);
INSERT INTO ILMCONFIG (ID, PARAM, VALUE, LASTMODIFIED) VALUES (ILMCONFIG_SEQUENCE.nextval, 'ONLINE_MOVE', 'FALSE', SYSTIMESTAMP);
INSERT INTO ILMCONFIG (ID, PARAM, VALUE, LASTMODIFIED) VALUES (ILMCONFIG_SEQUENCE.nextval, 'SKIP_WARM_STAGE', 'TRUE', SYSTIMESTAMP);

INSERT INTO ILMMANAGEDTABLE(ID, TABLENAME, TEMPTABLENAME, COLDTABLENAME, HOTRETENTION, WARMRETENTION, COLDRETENTION, WARMCOMPRESSION, COLDCOMPRESSION, DORMANTCOMPRESSION, MOVESEQUENCE, HOTSTATUS, WARMSTATUS, COLDSTATUS, LASTMODIFIED)
VALUES (ILMMANAGEDTABLE_SEQUENCE.nextval, 'PAYMENTINTERCHANGE', 'PAYMENTINTERCHANGETEMP', 'PAYMENTINTERCHANGECOLD', 1, 1, 1, 'OLTP', 'OLTP', 'OLTP', 1, null, null, null, sysdate);
commit;
