-----------------------------------------------------------------------------------------------------------------
-- Setup TPAYMENTINTERCHANGE tables
-----------------------------------------------------------------------------------------------------------------
CREATE TABLE TPAYMENTINTERCHANGE
(	 
     PAYMENTINTERCHANGEKEY   NUMBER(38,0) NOT NULL,
     INCOMING                CHAR(1) NOT NULL,
     DISPLAYINTERCHANGEID    VARCHAR2(128) NOT NULL,
     FILENAME                VARCHAR2(256),
     FILEFORMAT              VARCHAR2(128),
     TRANSPORTTIME           DATE,
     STATUS                  VARCHAR2(30),
     TRANSPORTDATA           BLOB DEFAULT EMPTY_BLOB(),
     DETAILS                 XMLTYPE,
     PROCESSINGDETAILS       XMLTYPE,
     BANKGROUPID             VARCHAR2(30) NOT NULL,
     CUSTOMERPAYMENTTYPEKEY  NUMBER(38,0),
     CLEARINGCONDITIONKEY    NUMBER(38,0) NOT NULL,
     BANKPAYMENTTYPEKEY      NUMBER(38,0),
     BANKINGENTITYKEY        NUMBER(38,0),
     ILMKEY                 TIMESTAMP default SYSTIMESTAMP NOT NULL,
     VERSION                NUMBER(38,0) NOT NULL ENABLE,
     WHENMODIFIED            DATE NOT NULL ENABLE,
     CONSTRAINT "PK_TPAYMENTINTERCHANGE" PRIMARY KEY ("PAYMENTINTERCHANGEKEY"))
XMLTYPE COLUMN DETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_HOT_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
XMLTYPE COLUMN PROCESSINGDETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_HOT_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
TABLESPACE ILM_HOT_TBS
PARTITION BY RANGE (ILMKEY) 
SUBPARTITION BY HASH(PAYMENTINTERCHANGEKEY) SUBPARTITIONS 16
(
    PARTITION P2015_10 VALUES LESS THAN (TO_DATE('2015-11-01', 'yyyy-MM-dd')),
    PARTITION P2015_11 VALUES LESS THAN (TO_DATE('2015-12-01', 'yyyy-MM-dd')),
    PARTITION P2015_12 VALUES LESS THAN (TO_DATE('2016-01-01', 'yyyy-MM-dd')),
    PARTITION P2016_01 VALUES LESS THAN (TO_DATE('2016-02-01', 'yyyy-MM-dd')),
    PARTITION P9999_12 VALUES LESS THAN (MAXVALUE)
);

-- add index
CREATE INDEX "I_TINTCH_TRANSPORTDATE" ON "TPAYMENTINTERCHANGE" ("TRANSPORTTIME") 
TABLESPACE "ILM_HOT_TBS";

CREATE INDEX "I_PMT_TINTERCHANGE_FILENAME" ON "TPAYMENTINTERCHANGE" ("FILENAME") 
TABLESPACE "ILM_HOT_TBS";

CREATE INDEX "I_PMT_TINTERCHANGE_STATUS" ON "TPAYMENTINTERCHANGE" ("STATUS") LOCAL
TABLESPACE "ILM_HOT_TBS";

-- allow row movement
ALTER TABLE TPAYMENTINTERCHANGE ENABLE ROW MOVEMENT;

-- Insert TPAYMENTINTERCHANGE
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
	values (timestamp'2015-10-15 09:00:00.123456789', 1430001,'T','OPF1430001','pacs.002 Interchange.xml','pacs.002.001.06',to_date('09-DEC-15 16:53:42','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-09T13:24:25Z</IntchngDtTm><IntchngRef>PACS.002-MIX-5</IntchngRef><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_RBS</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5014,null,-5002,2,to_date('09-DEC-15 16:53:42','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
	values (timestamp'2015-10-15 09:00:00.123456789', 1430002,'T','OPF1430002','pacs.002 Interchange.xml','pacs.002.001.06',to_date('09-DEC-15 16:53:42','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-09T13:24:25Z</IntchngDtTm><IntchngRef>PACS.002-MIX-5</IntchngRef><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_RBS</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5014,null,-5002,2,to_date('09-DEC-15 16:53:42','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
	values (timestamp'2015-11-15 09:00:00.123456789', 1430006,'T','OPF1430006','pacs.002 Interchange.xml','pacs.002.001.06',to_date('09-DEC-15 16:53:42','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-09T13:24:25Z</IntchngDtTm><IntchngRef>PACS.002-MIX-5</IntchngRef><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_RBS</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5014,null,-5002,2,to_date('09-DEC-15 16:53:42','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
	values (timestamp'2015-11-15 09:00:00.123456789', 1530000,'T','OPF1530000','pain.001-2TXN.xml','pain.001.001.05',to_date('10-DEC-15 15:29:58','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T07:27:10Z</IntchngDtTm><IntchngRef>ORGINTCHG-030</IntchngRef><NbOfTrns>2</NbOfTrns><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_CUST</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5004,null,-5002,2,to_date('10-DEC-15 15:29:59','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
	values (timestamp'2015-11-15 09:00:00.123456789', 1530102,'T','OPF1530102','pain.001-2TXN.xml','pain.001.001.05',to_date('10-DEC-15 15:50:24','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T07:27:10Z</IntchngDtTm><IntchngRef>ORGINTCHG-031</IntchngRef><NbOfTrns>2</NbOfTrns><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_CUST</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5004,null,-5002,2,to_date('10-DEC-15 15:50:24','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
	values (timestamp'2015-12-15 09:00:00.123456789', 1530103,'T','OPF1530103','pacs.002 Interchange.xml','pacs.002.001.06',to_date('10-DEC-15 16:03:13','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T13:24:25Z</IntchngDtTm><IntchngRef>PACS.002-MIX-5</IntchngRef><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_RBS</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5014,null,-5002,2,to_date('10-DEC-15 16:03:13','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
	values (timestamp'2015-12-15 09:00:00.123456789', 1530104,'T','OPF1530104','pain.001-2TXN.xml','pain.001.001.05',to_date('10-DEC-15 17:19:21','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T07:27:10Z</IntchngDtTm><IntchngRef>ORGINTCHG-033</IntchngRef><NbOfTrns>2</NbOfTrns><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_CUST</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5004,null,-5002,2,to_date('10-DEC-15 17:19:21','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
	values (timestamp'2015-12-15 09:00:00.123456789', 1530105,'F','OPF1530105','AcctEvt-BlueBank-DaDiOPF1530105.xml','pacs.008.001.04',to_date('10-DEC-15 17:19:23','DD-MON-RR HH24:MI:SS'),'Rejected','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T16:19:22Z</IntchngDtTm><IntchngRef>OPF1530105</IntchngRef><Mur>OPF1530105</Mur><NbOfTrns>1</NbOfTrns><RcvgPty>RBOSGB2LXXX</RcvgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Sbm><InitRunId>16801001</InitRunId></Sbm></Intchng>','OPFBankgroup',null,-5014,null,-5002,6,to_date('10-DEC-15 17:34:56','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
  values (timestamp'2015-12-15 09:00:00.123456789', 1530106,'T','OPF1530106','pacs.002 Interchange.xml','pacs.002.001.06',to_date('10-DEC-15 17:21:29','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T13:24:25Z</IntchngDtTm><IntchngRef>PACS.002-MIX-5</IntchngRef><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_RBS</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5014,null,-5002,2,to_date('10-DEC-15 17:21:29','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
	values (timestamp'2015-12-15 09:00:00.123456789', 1530107,'T','OPF1530107','pain.001-2TXN.xml','pain.001.001.05',to_date('10-DEC-15 17:45:50','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T07:27:10Z</IntchngDtTm><IntchngRef>ORGINTCHG-034</IntchngRef><NbOfTrns>2</NbOfTrns><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_CUST</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5004,null,-5002,2,to_date('10-DEC-15 17:45:50','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
	values (timestamp'2015-12-15 09:00:00.123456789', 1530108,'F','OPF1530108','AcctEvt-BlueBank-DaDiOPF1530108.xml','pacs.008.001.04',to_date('10-DEC-15 17:45:51','DD-MON-RR HH24:MI:SS'),'Rejected','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T16:45:51Z</IntchngDtTm><IntchngRef>OPF1530108</IntchngRef><Mur>OPF1530108</Mur><NbOfTrns>1</NbOfTrns><RcvgPty>RBOSGB2LXXX</RcvgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Sbm><InitRunId>16801002</InitRunId></Sbm></Intchng>','OPFBankgroup',null,-5014,null,-5002,6,to_date('10-DEC-15 18:06:18','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
	values (timestamp'2015-12-15 09:00:00.123456789', 1530109,'T','OPF1530 109','pacs.002 Interchange.xml','pacs.002.001.06',to_date('10-DEC-15 17:46:32','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T13:24:25Z</IntchngDtTm><IntchngRef>PACS.002-MIX-5</IntchngRef><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_RBS</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5014,null,-5002,2,to_date('10-DEC-15 17:46:32','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
	values (timestamp'2016-01-05 09:00:00.123456789', 1630002,'T','OPF1630002','pacs.002 Interchange.xml','pacs.002.001.06',to_date('11-DEC-15 17:09:24','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-10T13:24:25Z</IntchngDtTm><IntchngRef>PACS.002-MIX-5</IntchngRef><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_RBS</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5014,null,-5002,2,to_date('11-DEC-15 17:09:24','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
	values (timestamp'2016-01-05 09:00:00.123456789', 1630102,'T','OPF1630102','pacs.002 Interchange.xml','pacs.002.001.06',to_date('15-DEC-15 14:14:47','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-15T13:24:25Z</IntchngDtTm><IntchngRef>PACS.002-MIX-5</IntchngRef><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_RBS</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5014,null,-5002,2,to_date('15-DEC-15 14:14:47','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
	values (timestamp'2016-01-05 09:00:00.123456789', 1630100,'T','OPF1630100','pain.001-2TXN.xml','pain.001.001.05',to_date('15-DEC-15 14:00:26','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-15T07:27:10Z</IntchngDtTm><IntchngRef>ORGINTCHG-037</IntchngRef><NbOfTrns>2</NbOfTrns><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_CUST</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5004,null,-5002,2,to_date('15-DEC-15 14:00:27','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
  values (timestamp'2016-01-05 09:00:00.123456789', 1630101,'F','OPF1630101','AcctEvt-BlueBank-DaDiOPF1630101.xml','pacs.008.001.04',to_date('15-DEC-15 14:09:39','DD-MON-RR HH24:MI:SS'),'Rejected','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-15T13:09:18Z</IntchngDtTm><IntchngRef>OPF1630101</IntchngRef><Mur>OPF1630101</Mur><NbOfTrns>1</NbOfTrns><RcvgPty>RBOSGB2LXXX</RcvgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Sbm><InitRunId>17301000</InitRunId></Sbm></Intchng>','OPFBankgroup',null,-5014,null,-5002,6,to_date('15-DEC-15 14:19:04','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
	values (timestamp'2016-01-05 09:00:00.123456789', 1680100,'T','OPF1680100','pain.001-2TXN.xml','pain.001.001.05',to_date('15-DEC-15 16:29:36','DD-MON-RR HH24:MI:SS'),'Parsed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-15T07:27:10Z</IntchngDtTm><IntchngRef>ORGINTCHG-038</IntchngRef><NbOfTrns>2</NbOfTrns><RcvgPty>BLUEUK22XXX</RcvgPty><SndgPty>BB_CUST</SndgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Imprtnc>4</Imprtnc><PrtyLvl>4</PrtyLvl></Intchng>','OPFBankgroup',null,-5004,null,-5002,2,to_date('15-DEC-15 16:29:36','DD-MON-RR HH24:MI:SS'));
Insert into TPAYMENTINTERCHANGE (ILMKEY,PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
	values (timestamp'2016-01-05 09:00:00.123456789', 1680101,'F','OPF1680101','AcctEvt-BlueBank-DaDiOPF1680101.xml','pacs.008.001.04',to_date('15-DEC-15 16:29:40','DD-MON-RR HH24:MI:SS'),'Processed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-15T15:29:40Z</IntchngDtTm><IntchngRef>OPF1680101</IntchngRef><Mur>OPF1680101</Mur><NbOfTrns>1</NbOfTrns><RcvgPty>RBOSGB2LXXX</RcvgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Sbm><InitRunId>17801000</InitRunId></Sbm></Intchng>','OPFBankgroup',null,-5014,null,-5002,5,to_date('15-DEC-15 16:29:40','DD-MON-RR HH24:MI:SS'));

DECLARE
  pid NUMBER := 1000100;
BEGIN
  FOR i IN 1..300
  LOOP
    pid := pid + 1;
    Insert into TPAYMENTINTERCHANGE (ILMKEY, PAYMENTINTERCHANGEKEY,INCOMING,DISPLAYINTERCHANGEID,FILENAME,FILEFORMAT,TRANSPORTTIME,STATUS,DETAILS,PROCESSINGDETAILS,BANKGROUPID,CUSTOMERPAYMENTTYPEKEY,CLEARINGCONDITIONKEY,BANKPAYMENTTYPEKEY,BANKINGENTITYKEY,VERSION,WHENMODIFIED) 
    values (timestamp'2015-11-09 09:00:00.123456789', pid,'F','OPF1680101','AcctEvt-BlueBank-DaDiOPF1680101.xml','pacs.008.001.04',to_date('15-DEC-15 16:29:40','DD-MON-RR HH24:MI:SS'),'Processed','<?xml version="1.0" encoding="UTF-8"?><Intchng><IntchngDtTm>2015-12-15T15:29:40Z</IntchngDtTm><IntchngRef>OPF1680101</IntchngRef><Mur>OPF1680101</Mur><NbOfTrns>1</NbOfTrns><RcvgPty>RBOSGB2LXXX</RcvgPty></Intchng>','<?xml version="1.0" encoding="UTF-8"?><Intchng><Sbm><InitRunId>17801000</InitRunId></Sbm></Intchng>','OPFBankgroup',null,-5014,null,-5002,5,to_date('15-DEC-15 16:29:40','DD-MON-RR HH24:MI:SS'));
  END LOOP;
END;
/

commit;

-----------------------------------------------------------------------------------------------------------------
-- Setup TPAYMENTINTERCHANGECOLD tables
-----------------------------------------------------------------------------------------------------------------
CREATE TABLE TPAYMENTINTERCHANGECOLD
(	 
     PAYMENTINTERCHANGEKEY   NUMBER(38,0) NOT NULL,
     INCOMING                CHAR(1) NOT NULL,
     DISPLAYINTERCHANGEID    VARCHAR2(128) NOT NULL,
     FILENAME                VARCHAR2(256),
     FILEFORMAT              VARCHAR2(128),
     TRANSPORTTIME           DATE,
     STATUS                  VARCHAR2(30),
     TRANSPORTDATA           BLOB DEFAULT EMPTY_BLOB(),
     DETAILS                 XMLTYPE,
     PROCESSINGDETAILS       XMLTYPE,
     BANKGROUPID             VARCHAR2(30) NOT NULL,
     CUSTOMERPAYMENTTYPEKEY  NUMBER(38,0),
     CLEARINGCONDITIONKEY    NUMBER(38,0) NOT NULL,
     BANKPAYMENTTYPEKEY      NUMBER(38,0),
     BANKINGENTITYKEY        NUMBER(38,0),
     ILMKEY                 TIMESTAMP default TO_TIMESTAMP('10-DEC-2015:10:10:10','DD-MON-YYYY:HH24:MI:SS'),
     VERSION                NUMBER(38,0) NOT NULL ENABLE,
     WHENMODIFIED            DATE NOT NULL ENABLE,
     CONSTRAINT "PK_TPAYMENTINTERCHANGECOLD" PRIMARY KEY ("PAYMENTINTERCHANGEKEY"))
XMLTYPE COLUMN DETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_COLD_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
XMLTYPE COLUMN PROCESSINGDETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_COLD_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
TABLESPACE ILM_COLD_TBS
PARTITION BY RANGE (ILMKEY) 
SUBPARTITION BY HASH(PAYMENTINTERCHANGEKEY) SUBPARTITIONS 16
(
    PARTITION P2015_10 VALUES LESS THAN (TO_DATE('2015-11-01', 'yyyy-MM-dd')),
    PARTITION P9999_12 VALUES LESS THAN (MAXVALUE)
);

-- add index
CREATE INDEX "I_TINTCHC_TRANSPORTDATE" ON "TPAYMENTINTERCHANGECOLD" ("TRANSPORTTIME") 
TABLESPACE "ILM_COLD_TBS";

CREATE INDEX "I_PMT_TINTERCHANGEC_FILENAME" ON "TPAYMENTINTERCHANGECOLD" ("FILENAME") 
TABLESPACE "ILM_COLD_TBS";

CREATE INDEX "I_PMT_TINTERCHANGEC_STATUS" ON "TPAYMENTINTERCHANGECOLD" ("STATUS") LOCAL
TABLESPACE "ILM_COLD_TBS";


-----------------------------------------------------------------------------------------------------------------
-- Setup TPAYMENTINTERCHANGETEMP tables
-----------------------------------------------------------------------------------------------------------------
-- create temp table
CREATE TABLE TPAYMENTINTERCHANGETEMP
(	 
     PAYMENTINTERCHANGEKEY   NUMBER(38,0) NOT NULL,
     INCOMING                CHAR(1) NOT NULL,
     DISPLAYINTERCHANGEID    VARCHAR2(128) NOT NULL,
     FILENAME                VARCHAR2(256),
     FILEFORMAT              VARCHAR2(128),
     TRANSPORTTIME           DATE,
     STATUS                  VARCHAR2(30),
     TRANSPORTDATA           BLOB DEFAULT EMPTY_BLOB(),
     DETAILS                 XMLTYPE,
     PROCESSINGDETAILS       XMLTYPE,
     BANKGROUPID             VARCHAR2(30) NOT NULL,
     CUSTOMERPAYMENTTYPEKEY  NUMBER(38,0),
     CLEARINGCONDITIONKEY    NUMBER(38,0) NOT NULL,
     BANKPAYMENTTYPEKEY      NUMBER(38,0),
     BANKINGENTITYKEY        NUMBER(38,0),
     ILMKEY                 TIMESTAMP default TO_TIMESTAMP('10-DEC-2015:10:10:10','DD-MON-YYYY:HH24:MI:SS'),
     VERSION                NUMBER(38,0) NOT NULL ENABLE,
     WHENMODIFIED            DATE NOT NULL ENABLE,
     CONSTRAINT "PK_TPAYMENTINTERCHANGETEMP" PRIMARY KEY ("PAYMENTINTERCHANGEKEY"))
XMLTYPE COLUMN DETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_COLD_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
XMLTYPE COLUMN PROCESSINGDETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_COLD_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
TABLESPACE ILM_COLD_TBS
PARTITION BY HASH(PAYMENTINTERCHANGEKEY) PARTITIONS 16;


-----------------------------------------------------------------------------------------------------------------
-- Setup TPAYMENTTRANSACTION tables
-----------------------------------------------------------------------------------------------------------------
CREATE TABLE "TPAYMENTTRANSACTION" 
   (	"PAYMENTTRANSACTIONKEY" NUMBER(38,0), 
	"DISPLAYTRANSACTIONID" VARCHAR2(128 CHAR), 
	"STATUS" VARCHAR2(30 CHAR), 
	"DETAILS" "SYS"."XMLTYPE" , 
	"PROCESSINGDETAILS" "SYS"."XMLTYPE" , 
	"BANKKEY" NUMBER(38,0), 
	"BANKGROUPID" VARCHAR2(30 CHAR), 
	"OUTGINTCHGCLEARINGCNDTNKEY" NUMBER(38,0), 
	"OPICKEY" NUMBER(38,0), 
	"OUTGINSTRBUSINESSPRTCPNTKEY" NUMBER(38,0), 
	"OUTGINSTRSETTLEMENTPRTCPNTKEY" NUMBER(38,0), 
	"INCOMINGINSTRUCTIONKEY" NUMBER(38,0), 
	"CANCELRECONCILIATIONKEY" NUMBER(38,0), 
	"REJECTRECONCILIATIONKEY" NUMBER(38,0), 
	"INCOMINGTRANSACTIONGROUPKEY" NUMBER(38,0), 
	"OUTGOINGTRANSACTIONGROUPKEY" NUMBER(38,0), 
	"BANKPAYMENTTYPEKEY" NUMBER(38,0), 
	"BANKINGACCOUNTKEY" NUMBER(38,0), 
	"RECEIVINGENTITYKEY" NUMBER(38,0), 
	"VERSION" NUMBER(38,0), 
	"WHENMODIFIED" DATE, 
	"CLASSIFICATIONIDX" VARCHAR2(256 CHAR), 
	"ENDTOENDIDIDX" VARCHAR2(256 CHAR), 
	"FIRSTINSTRUCTINGAGENTTRNIDIDX" VARCHAR2(256 CHAR), 
	"SETTLEMENTAMOUNTIDX" NUMBER(38,5), 
	"SETTLEMENTCURRENCYIDX" VARCHAR2(256 CHAR), 
	"INCOMINGSETTLEMENTDAYIDX" VARCHAR2(10 CHAR), 
	"SETTLEMENTDAYIDX" VARCHAR2(10 CHAR), 
	"DEBITCREDITINDICATORIDX" CHAR(1 CHAR), 
	"PROCESSINGSCHEMEIDX" VARCHAR2(256 CHAR), 
	"INSTRUCTEDDAYIDX" VARCHAR2(10 CHAR), 
	"RTRANSACTIONQUALIFICATIONIDX" VARCHAR2(256 CHAR), 
	"ORIGINALENDTOENDIDIDX" VARCHAR2(256 CHAR), 
	"PRIORITYIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYNAMEIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYACCOUNTIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYAGENTIDIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYAGENT2IDIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYAGENT3IDIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYAGENT4IDIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYAGENT5IDIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYNAMEIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYACCOUNTIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYAGENTIDIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYAGENT2IDIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYAGENT3IDIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYAGENT4IDIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYAGENT5IDIDX" VARCHAR2(256 CHAR), 
	"PROCESSINGDAYIDX" VARCHAR2(10 CHAR), 
	"INCOMINGSETTLEMENTAMOUNTIDX" NUMBER(38,5), 
	"INCOMINGSETTLEMENTCURRENCYIDX" VARCHAR2(256 CHAR), 
	"ATTACHMENTCOLLECTIONIDIDX" NUMBER(38,0), 
	"ONUSFLAGIPX" CHAR(1 CHAR), 
	"DUPLICATECHECKHASHIPX" VARCHAR2(256 CHAR), 
	"UNROUTABLEFROMINSTRUCTIONIPX" CHAR(1 CHAR), 
	"OUTBOUNDIPX" CHAR(1 CHAR), 
	"OMITTEDFLAGIPX" CHAR(1 CHAR), 
	"RISKFILTERCHECKTIMESTAMPIPX" DATE,
  "ILMKEY" TIMESTAMP default SYSTIMESTAMP NOT NULL
   ) 
  XMLTYPE COLUMN DETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_HOT_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
  XMLTYPE COLUMN PROCESSINGDETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_HOT_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
  TABLESPACE "ILM_HOT_TBS"
  PARTITION BY RANGE (ILMKEY) 
  SUBPARTITION BY HASH(PAYMENTTRANSACTIONKEY) SUBPARTITIONS 16
  (
      PARTITION P2015_10 VALUES LESS THAN (TO_DATE('2015-11-01', 'yyyy-MM-dd')),
      PARTITION P2015_11 VALUES LESS THAN (TO_DATE('2015-12-01', 'yyyy-MM-dd')),
      PARTITION P2015_12 VALUES LESS THAN (TO_DATE('2016-01-01', 'yyyy-MM-dd')),
      PARTITION P9999_12 VALUES LESS THAN (MAXVALUE)
  );

-- add index
CREATE INDEX "I_TXN_STATUS" ON "TPAYMENTTRANSACTION" ("STATUS")  TABLESPACE "ILM_HOT_TBS";
CREATE INDEX "I_TXN_OPIC" ON "TPAYMENTTRANSACTION" ("OPICKEY")  TABLESPACE "ILM_HOT_TBS";
CREATE INDEX "I_TXN_INSTRUCTION" ON "TPAYMENTTRANSACTION" ("INCOMINGINSTRUCTIONKEY") TABLESPACE "ILM_HOT_TBS";
CREATE INDEX "I_TXN_SETTLEMENTDAYIDX" ON "TPAYMENTTRANSACTION" ("SETTLEMENTAMOUNTIDX") TABLESPACE "ILM_HOT_TBS" ;
CREATE INDEX "I_TXN_INCSETTLMTDAY" ON "TPAYMENTTRANSACTION" ("INCOMINGSETTLEMENTDAYIDX") TABLESPACE "ILM_HOT_TBS" ;
CREATE INDEX "I_TXN_ENDTOENDID" ON "TPAYMENTTRANSACTION" ("BANKKEY", "ENDTOENDIDIDX") TABLESPACE "ILM_HOT_TBS" ;
CREATE INDEX "I_TXN_CREDITPARTYACCOUNTIDX" ON "TPAYMENTTRANSACTION" (UPPER("CREDITPARTYACCOUNTIDX")) TABLESPACE "ILM_HOT_TBS" ;
CREATE INDEX "I_TXN_DEBITPARTYACCOUNTIDX" ON "TPAYMENTTRANSACTION" (UPPER("DEBITPARTYACCOUNTIDX")) TABLESPACE "ILM_HOT_TBS" ;

-- add constraint
ALTER TABLE "TPAYMENTTRANSACTION" ADD CONSTRAINT "U_PAYMENTTRANSACTION" UNIQUE ("DISPLAYTRANSACTIONID")
USING INDEX (CREATE UNIQUE INDEX "U_TRNDISPLAYID" ON "TPAYMENTTRANSACTION" ("DISPLAYTRANSACTIONID") TABLESPACE "ILM_HOT_TBS" )  ENABLE;

ALTER TABLE "TPAYMENTTRANSACTION" ADD CONSTRAINT "PK_PAYMENTTRANSACTION" PRIMARY KEY ("PAYMENTTRANSACTIONKEY") ENABLE;

-- add not null constraints
ALTER TABLE "TPAYMENTTRANSACTION" MODIFY ("WHENMODIFIED" NOT NULL ENABLE);
ALTER TABLE "TPAYMENTTRANSACTION" MODIFY ("VERSION" NOT NULL ENABLE);
ALTER TABLE "TPAYMENTTRANSACTION" MODIFY ("BANKGROUPID" NOT NULL ENABLE);
ALTER TABLE "TPAYMENTTRANSACTION" MODIFY ("BANKKEY" NOT NULL ENABLE);
ALTER TABLE "TPAYMENTTRANSACTION" MODIFY ("DISPLAYTRANSACTIONID" NOT NULL ENABLE);
ALTER TABLE "TPAYMENTTRANSACTION" MODIFY ("PAYMENTTRANSACTIONKEY" NOT NULL ENABLE);

-- insert records to TPAYMENTTRANSACTION
DECLARE
  pid NUMBER := 130000001;
BEGIN
  FOR i IN 1..100
  LOOP
    pid := pid + 1;
    Insert into TPAYMENTTRANSACTION (ILMKEY,PAYMENTTRANSACTIONKEY,DISPLAYTRANSACTIONID,STATUS,DETAILS,PROCESSINGDETAILS,BANKKEY,BANKGROUPID,OUTGINTCHGCLEARINGCNDTNKEY,OPICKEY,OUTGINSTRBUSINESSPRTCPNTKEY,OUTGINSTRSETTLEMENTPRTCPNTKEY,INCOMINGINSTRUCTIONKEY,CANCELRECONCILIATIONKEY,REJECTRECONCILIATIONKEY,INCOMINGTRANSACTIONGROUPKEY,OUTGOINGTRANSACTIONGROUPKEY,BANKPAYMENTTYPEKEY,BANKINGACCOUNTKEY,RECEIVINGENTITYKEY,VERSION,WHENMODIFIED,CLASSIFICATIONIDX,ENDTOENDIDIDX,FIRSTINSTRUCTINGAGENTTRNIDIDX,SETTLEMENTAMOUNTIDX,SETTLEMENTCURRENCYIDX,INCOMINGSETTLEMENTDAYIDX,SETTLEMENTDAYIDX,DEBITCREDITINDICATORIDX,PROCESSINGSCHEMEIDX,INSTRUCTEDDAYIDX,RTRANSACTIONQUALIFICATIONIDX,ORIGINALENDTOENDIDIDX,PRIORITYIDX,DEBITPARTYNAMEIDX,DEBITPARTYACCOUNTIDX,DEBITPARTYAGENTIDIDX,DEBITPARTYAGENT2IDIDX,DEBITPARTYAGENT3IDIDX,DEBITPARTYAGENT4IDIDX,DEBITPARTYAGENT5IDIDX,CREDITPARTYNAMEIDX,CREDITPARTYACCOUNTIDX,CREDITPARTYAGENTIDIDX,CREDITPARTYAGENT2IDIDX,CREDITPARTYAGENT3IDIDX,CREDITPARTYAGENT4IDIDX,CREDITPARTYAGENT5IDIDX,PROCESSINGDAYIDX,INCOMINGSETTLEMENTAMOUNTIDX,INCOMINGSETTLEMENTCURRENCYIDX,ATTACHMENTCOLLECTIONIDIDX,ONUSFLAGIPX,DUPLICATECHECKHASHIPX,UNROUTABLEFROMINSTRUCTIONIPX,OUTBOUNDIPX,OMITTEDFLAGIPX,RISKFILTERCHECKTIMESTAMPIPX) 
    values (timestamp'2015-10-01 09:00:00.123456789', pid,'OPF1'||pid,'IncomingInterchangeRejected','<?xml version="1.0" encoding="UTF-8"?><Trn><Cdtr><Nm>Mr SMITH</Nm><PstlAdr><AdrLine>32 Miller St</AdrLine><AdrLine>Dublin</AdrLine><Ctry>IE</Ctry></PstlAdr></Cdtr><CdtrAcct><AcctId><Id>IE29AIBK93115212345678</Id><IdTp>IBAN</IdTp></AcctId></CdtrAcct><CdtrAgt><FinInstnId><Id><Id>RBOSGB2LXXX</Id><Tp>BIC</Tp></Id></FinInstnId></CdtrAgt><ChrgBr>SHAR</ChrgBr><Clssfn>CreditTransfer</Clssfn><DbtCdtInd>C</DbtCdtInd><Dbtr><Nm>Mrs Cambells</Nm><PstlAdr><Ctry>UK</Ctry><StrtNm>123 Aurther St</StrtNm><TwnNm>Aberdeen</TwnNm></PstlAdr></Dbtr><DbtrAcct><AcctId><Id>4002</Id><IdTp>Proprietary</IdTp></AcctId></DbtrAcct><DbtrAgt><FinInstnId><Id><Id>1234</Id><Tp>BIC</Tp></Id></FinInstnId></DbtrAgt><InSttlmDay>2015-11-13</InSttlmDay><InstdAmt Ccy="USD">1003.00000</InstdAmt><IntrBkSttlmAmt Ccy="USD">1003.00000</IntrBkSttlmAmt><TrnRef><EndToEndId>ORGTXN-001</EndToEndId><FrstInstgTrnId>OPF130000001</FrstInstgTrnId><InstgTrnId>OPF130000001</InstgTrnId></TrnRef></Trn>','<?xml version="1.0" encoding="UTF-8"?><Trn><Prcss><MnlActn><Issue>#Mon Dec 07 15:09:31 CET 2015
messageNumber=70053
domain=opfpayment/exchangeoperator
</Issue><Tp>ApproveUnroutable</Tp></MnlActn><TmpltNm>P40UnroutableTransaction</TmpltNm></Prcss><Rtg><RtgCpdAgntFlg>false</RtgCpdAgntFlg><UnrtblFrmInstr>true</UnrtblFrmInstr><frstMtchdRl>-5010</frstMtchdRl></Rtg><RtgAgt><Id>RBOSGB2LXXX</Id><IdTp>BIC</IdTp></RtgAgt></Trn>',-5002,'OPFBankgroup',null,11800007,null,null,1240001,null,null,null,null,null,null,null,17,to_date('07-DEC-15 20:05:57','DD-MON-RR HH24:MI:SS'),'CreditTransfer','ORGTXN-001','OPF130000001',1003,'USD','2015-11-13',null,'C',null,null,null,null,null,'Mrs Cambells','4002','1234',null,null,null,null,'Mr SMITH','IE29AIBK93115212345678','RBOSGB2LXXX',null,null,null,null,null,null,null,null,null,null,'T',null,null,null);
  END LOOP;
  
  pid := 130100000;
  FOR i IN 1..100
  LOOP
    pid := pid + 1;
    Insert into TPAYMENTTRANSACTION (ILMKEY,PAYMENTTRANSACTIONKEY,DISPLAYTRANSACTIONID,STATUS,DETAILS,PROCESSINGDETAILS,BANKKEY,BANKGROUPID,OUTGINTCHGCLEARINGCNDTNKEY,OPICKEY,OUTGINSTRBUSINESSPRTCPNTKEY,OUTGINSTRSETTLEMENTPRTCPNTKEY,INCOMINGINSTRUCTIONKEY,CANCELRECONCILIATIONKEY,REJECTRECONCILIATIONKEY,INCOMINGTRANSACTIONGROUPKEY,OUTGOINGTRANSACTIONGROUPKEY,BANKPAYMENTTYPEKEY,BANKINGACCOUNTKEY,RECEIVINGENTITYKEY,VERSION,WHENMODIFIED,CLASSIFICATIONIDX,ENDTOENDIDIDX,FIRSTINSTRUCTINGAGENTTRNIDIDX,SETTLEMENTAMOUNTIDX,SETTLEMENTCURRENCYIDX,INCOMINGSETTLEMENTDAYIDX,SETTLEMENTDAYIDX,DEBITCREDITINDICATORIDX,PROCESSINGSCHEMEIDX,INSTRUCTEDDAYIDX,RTRANSACTIONQUALIFICATIONIDX,ORIGINALENDTOENDIDIDX,PRIORITYIDX,DEBITPARTYNAMEIDX,DEBITPARTYACCOUNTIDX,DEBITPARTYAGENTIDIDX,DEBITPARTYAGENT2IDIDX,DEBITPARTYAGENT3IDIDX,DEBITPARTYAGENT4IDIDX,DEBITPARTYAGENT5IDIDX,CREDITPARTYNAMEIDX,CREDITPARTYACCOUNTIDX,CREDITPARTYAGENTIDIDX,CREDITPARTYAGENT2IDIDX,CREDITPARTYAGENT3IDIDX,CREDITPARTYAGENT4IDIDX,CREDITPARTYAGENT5IDIDX,PROCESSINGDAYIDX,INCOMINGSETTLEMENTAMOUNTIDX,INCOMINGSETTLEMENTCURRENCYIDX,ATTACHMENTCOLLECTIONIDIDX,ONUSFLAGIPX,DUPLICATECHECKHASHIPX,UNROUTABLEFROMINSTRUCTIONIPX,OUTBOUNDIPX,OMITTEDFLAGIPX,RISKFILTERCHECKTIMESTAMPIPX) 
    values (timestamp'2015-11-01 09:00:00.123456789', pid,'OPF1'||pid,'IncomingInterchangeRejected','<?xml version="1.0" encoding="UTF-8"?><Trn><Cdtr><Nm>Mr SMITH</Nm><PstlAdr><AdrLine>32 Miller St</AdrLine><AdrLine>Dublin</AdrLine><Ctry>IE</Ctry></PstlAdr></Cdtr><CdtrAcct><AcctId><Id>IE29AIBK93115212345678</Id><IdTp>IBAN</IdTp></AcctId></CdtrAcct><CdtrAgt><FinInstnId><Id><Id>RBOSGB2LXXX</Id><Tp>BIC</Tp></Id></FinInstnId></CdtrAgt><ChrgBr>SHAR</ChrgBr><Clssfn>CreditTransfer</Clssfn><DbtCdtInd>C</DbtCdtInd><Dbtr><Nm>Mrs Cambells</Nm><PstlAdr><Ctry>UK</Ctry><StrtNm>123 Aurther St</StrtNm><TwnNm>Aberdeen</TwnNm></PstlAdr></Dbtr><DbtrAcct><AcctId><Id>4002</Id><IdTp>Proprietary</IdTp></AcctId></DbtrAcct><DbtrAgt><FinInstnId><Id><Id>1234</Id><Tp>BIC</Tp></Id></FinInstnId></DbtrAgt><InSttlmDay>2015-11-13</InSttlmDay><InstdAmt Ccy="USD">1003.00000</InstdAmt><IntrBkSttlmAmt Ccy="USD">1003.00000</IntrBkSttlmAmt><TrnRef><EndToEndId>ORGTXN-001</EndToEndId><FrstInstgTrnId>OPF130000001</FrstInstgTrnId><InstgTrnId>OPF130000001</InstgTrnId></TrnRef></Trn>','<?xml version="1.0" encoding="UTF-8"?><Trn><Prcss><MnlActn><Issue>#Mon Dec 07 15:09:31 CET 2015
messageNumber=70053
domain=opfpayment/exchangeoperator
</Issue><Tp>ApproveUnroutable</Tp></MnlActn><TmpltNm>P40UnroutableTransaction</TmpltNm></Prcss><Rtg><RtgCpdAgntFlg>false</RtgCpdAgntFlg><UnrtblFrmInstr>true</UnrtblFrmInstr><frstMtchdRl>-5010</frstMtchdRl></Rtg><RtgAgt><Id>RBOSGB2LXXX</Id><IdTp>BIC</IdTp></RtgAgt></Trn>',-5002,'OPFBankgroup',null,11800007,null,null,1240001,null,null,null,null,null,null,null,17,to_date('07-DEC-15 20:05:57','DD-MON-RR HH24:MI:SS'),'CreditTransfer','ORGTXN-001','OPF130000001',1003,'USD','2015-11-13',null,'C',null,null,null,null,null,'Mrs Cambells','4002','1234',null,null,null,null,'Mr SMITH','IE29AIBK93115212345678','RBOSGB2LXXX',null,null,null,null,null,null,null,null,null,null,'T',null,null,null);
  END LOOP;
  
  pid := 130200000;
  FOR i IN 1..100
  LOOP
    pid := pid + 1;
    Insert into TPAYMENTTRANSACTION (ILMKEY,PAYMENTTRANSACTIONKEY,DISPLAYTRANSACTIONID,STATUS,DETAILS,PROCESSINGDETAILS,BANKKEY,BANKGROUPID,OUTGINTCHGCLEARINGCNDTNKEY,OPICKEY,OUTGINSTRBUSINESSPRTCPNTKEY,OUTGINSTRSETTLEMENTPRTCPNTKEY,INCOMINGINSTRUCTIONKEY,CANCELRECONCILIATIONKEY,REJECTRECONCILIATIONKEY,INCOMINGTRANSACTIONGROUPKEY,OUTGOINGTRANSACTIONGROUPKEY,BANKPAYMENTTYPEKEY,BANKINGACCOUNTKEY,RECEIVINGENTITYKEY,VERSION,WHENMODIFIED,CLASSIFICATIONIDX,ENDTOENDIDIDX,FIRSTINSTRUCTINGAGENTTRNIDIDX,SETTLEMENTAMOUNTIDX,SETTLEMENTCURRENCYIDX,INCOMINGSETTLEMENTDAYIDX,SETTLEMENTDAYIDX,DEBITCREDITINDICATORIDX,PROCESSINGSCHEMEIDX,INSTRUCTEDDAYIDX,RTRANSACTIONQUALIFICATIONIDX,ORIGINALENDTOENDIDIDX,PRIORITYIDX,DEBITPARTYNAMEIDX,DEBITPARTYACCOUNTIDX,DEBITPARTYAGENTIDIDX,DEBITPARTYAGENT2IDIDX,DEBITPARTYAGENT3IDIDX,DEBITPARTYAGENT4IDIDX,DEBITPARTYAGENT5IDIDX,CREDITPARTYNAMEIDX,CREDITPARTYACCOUNTIDX,CREDITPARTYAGENTIDIDX,CREDITPARTYAGENT2IDIDX,CREDITPARTYAGENT3IDIDX,CREDITPARTYAGENT4IDIDX,CREDITPARTYAGENT5IDIDX,PROCESSINGDAYIDX,INCOMINGSETTLEMENTAMOUNTIDX,INCOMINGSETTLEMENTCURRENCYIDX,ATTACHMENTCOLLECTIONIDIDX,ONUSFLAGIPX,DUPLICATECHECKHASHIPX,UNROUTABLEFROMINSTRUCTIONIPX,OUTBOUNDIPX,OMITTEDFLAGIPX,RISKFILTERCHECKTIMESTAMPIPX) 
    values (timestamp'2015-12-01 09:00:00.123456789', pid,'OPF1'||pid,'IncomingInterchangeRejected','<?xml version="1.0" encoding="UTF-8"?><Trn><Cdtr><Nm>Mr SMITH</Nm><PstlAdr><AdrLine>32 Miller St</AdrLine><AdrLine>Dublin</AdrLine><Ctry>IE</Ctry></PstlAdr></Cdtr><CdtrAcct><AcctId><Id>IE29AIBK93115212345678</Id><IdTp>IBAN</IdTp></AcctId></CdtrAcct><CdtrAgt><FinInstnId><Id><Id>RBOSGB2LXXX</Id><Tp>BIC</Tp></Id></FinInstnId></CdtrAgt><ChrgBr>SHAR</ChrgBr><Clssfn>CreditTransfer</Clssfn><DbtCdtInd>C</DbtCdtInd><Dbtr><Nm>Mrs Cambells</Nm><PstlAdr><Ctry>UK</Ctry><StrtNm>123 Aurther St</StrtNm><TwnNm>Aberdeen</TwnNm></PstlAdr></Dbtr><DbtrAcct><AcctId><Id>4002</Id><IdTp>Proprietary</IdTp></AcctId></DbtrAcct><DbtrAgt><FinInstnId><Id><Id>1234</Id><Tp>BIC</Tp></Id></FinInstnId></DbtrAgt><InSttlmDay>2015-11-13</InSttlmDay><InstdAmt Ccy="USD">1003.00000</InstdAmt><IntrBkSttlmAmt Ccy="USD">1003.00000</IntrBkSttlmAmt><TrnRef><EndToEndId>ORGTXN-001</EndToEndId><FrstInstgTrnId>OPF130000001</FrstInstgTrnId><InstgTrnId>OPF130000001</InstgTrnId></TrnRef></Trn>','<?xml version="1.0" encoding="UTF-8"?><Trn><Prcss><MnlActn><Issue>#Mon Dec 07 15:09:31 CET 2015
messageNumber=70053
domain=opfpayment/exchangeoperator
</Issue><Tp>ApproveUnroutable</Tp></MnlActn><TmpltNm>P40UnroutableTransaction</TmpltNm></Prcss><Rtg><RtgCpdAgntFlg>false</RtgCpdAgntFlg><UnrtblFrmInstr>true</UnrtblFrmInstr><frstMtchdRl>-5010</frstMtchdRl></Rtg><RtgAgt><Id>RBOSGB2LXXX</Id><IdTp>BIC</IdTp></RtgAgt></Trn>',-5002,'OPFBankgroup',null,11800007,null,null,1240001,null,null,null,null,null,null,null,17,to_date('07-DEC-15 20:05:57','DD-MON-RR HH24:MI:SS'),'CreditTransfer','ORGTXN-001','OPF130000001',1003,'USD','2015-11-13',null,'C',null,null,null,null,null,'Mrs Cambells','4002','1234',null,null,null,null,'Mr SMITH','IE29AIBK93115212345678','RBOSGB2LXXX',null,null,null,null,null,null,null,null,null,null,'T',null,null,null);
  END LOOP;
  
  pid := 130400000;
  FOR i IN 1..100
  LOOP
    pid := pid + 1;
    Insert into TPAYMENTTRANSACTION (ILMKEY,PAYMENTTRANSACTIONKEY,DISPLAYTRANSACTIONID,STATUS,DETAILS,PROCESSINGDETAILS,BANKKEY,BANKGROUPID,OUTGINTCHGCLEARINGCNDTNKEY,OPICKEY,OUTGINSTRBUSINESSPRTCPNTKEY,OUTGINSTRSETTLEMENTPRTCPNTKEY,INCOMINGINSTRUCTIONKEY,CANCELRECONCILIATIONKEY,REJECTRECONCILIATIONKEY,INCOMINGTRANSACTIONGROUPKEY,OUTGOINGTRANSACTIONGROUPKEY,BANKPAYMENTTYPEKEY,BANKINGACCOUNTKEY,RECEIVINGENTITYKEY,VERSION,WHENMODIFIED,CLASSIFICATIONIDX,ENDTOENDIDIDX,FIRSTINSTRUCTINGAGENTTRNIDIDX,SETTLEMENTAMOUNTIDX,SETTLEMENTCURRENCYIDX,INCOMINGSETTLEMENTDAYIDX,SETTLEMENTDAYIDX,DEBITCREDITINDICATORIDX,PROCESSINGSCHEMEIDX,INSTRUCTEDDAYIDX,RTRANSACTIONQUALIFICATIONIDX,ORIGINALENDTOENDIDIDX,PRIORITYIDX,DEBITPARTYNAMEIDX,DEBITPARTYACCOUNTIDX,DEBITPARTYAGENTIDIDX,DEBITPARTYAGENT2IDIDX,DEBITPARTYAGENT3IDIDX,DEBITPARTYAGENT4IDIDX,DEBITPARTYAGENT5IDIDX,CREDITPARTYNAMEIDX,CREDITPARTYACCOUNTIDX,CREDITPARTYAGENTIDIDX,CREDITPARTYAGENT2IDIDX,CREDITPARTYAGENT3IDIDX,CREDITPARTYAGENT4IDIDX,CREDITPARTYAGENT5IDIDX,PROCESSINGDAYIDX,INCOMINGSETTLEMENTAMOUNTIDX,INCOMINGSETTLEMENTCURRENCYIDX,ATTACHMENTCOLLECTIONIDIDX,ONUSFLAGIPX,DUPLICATECHECKHASHIPX,UNROUTABLEFROMINSTRUCTIONIPX,OUTBOUNDIPX,OMITTEDFLAGIPX,RISKFILTERCHECKTIMESTAMPIPX) 
    values (timestamp'2016-02-01 09:00:00.123456789', pid,'OPF1'||pid,'IncomingInterchangeRejected','<?xml version="1.0" encoding="UTF-8"?><Trn><Cdtr><Nm>Mr SMITH</Nm><PstlAdr><AdrLine>32 Miller St</AdrLine><AdrLine>Dublin</AdrLine><Ctry>IE</Ctry></PstlAdr></Cdtr><CdtrAcct><AcctId><Id>IE29AIBK93115212345678</Id><IdTp>IBAN</IdTp></AcctId></CdtrAcct><CdtrAgt><FinInstnId><Id><Id>RBOSGB2LXXX</Id><Tp>BIC</Tp></Id></FinInstnId></CdtrAgt><ChrgBr>SHAR</ChrgBr><Clssfn>CreditTransfer</Clssfn><DbtCdtInd>C</DbtCdtInd><Dbtr><Nm>Mrs Cambells</Nm><PstlAdr><Ctry>UK</Ctry><StrtNm>123 Aurther St</StrtNm><TwnNm>Aberdeen</TwnNm></PstlAdr></Dbtr><DbtrAcct><AcctId><Id>4002</Id><IdTp>Proprietary</IdTp></AcctId></DbtrAcct><DbtrAgt><FinInstnId><Id><Id>1234</Id><Tp>BIC</Tp></Id></FinInstnId></DbtrAgt><InSttlmDay>2015-12-07</InSttlmDay><InstdAgt><FinInstnId><Id><Id>RBOSGB2LXXX</Id><Tp>BIC</Tp></Id></FinInstnId></InstdAgt><InstdAmt Ccy="EUR">5504.00000</InstdAmt><IntrBkSttlmAmt Ccy="EUR">5504.00000</IntrBkSttlmAmt><PmtTpInf><LclInstrm><Cd>Kilt</Cd></LclInstrm></PmtTpInf><SttlmDay>2015-12-07</SttlmDay><TrnRef><EndToEndId>ORGTXN-008</EndToEndId><FrstInstgTrnId>OPF135010011</FrstInstgTrnId><InstgTrnId>OPF135010011</InstgTrnId></TrnRef></Trn>','<?xml version="1.0" encoding="UTF-8"?><Trn><ErlstSubmTm>585532800000</ErlstSubmTm><ExpctdDwhsTm>1449100800000</ExpctdDwhsTm><LtstSubmTm>1449529200000</LtstSubmTm><OnUs>false</OnUs><PrtyLvl>4</PrtyLvl><RgtRule>RBS SWIFTMX</RgtRule><Rtg><RtgCpdAgntFlg>true</RtgCpdAgntFlg><Schm>CSCB</Schm><frstMtchdRl>-5010</frstMtchdRl><instdAgtLnk>CreditPartyAgent</instdAgtLnk><mtchdRlKey>-5010</mtchdRlKey></Rtg><RtgAgt><Id>RBOSGB2LXXX</Id><IdTp>BIC</IdTp><Lnk>CreditPartyAgent</Lnk></RtgAgt></Trn>',-5002,'OPFBankgroup',-5014,12300004,-5008,-5008,1290125,null,null,null,null,null,null,-5002,4,to_date('07-DEC-15 20:05:57','DD-MON-RR HH24:MI:SS'),'CreditTransfer','ORGTXN-008','OPF135010011',5504,'EUR','2015-12-07','2015-12-07','C',null,null,null,null,null,'Mrs Cambells','4002','1234',null,null,null,null,'Mr SMITH','IE29AIBK93115212345678','RBOSGB2LXXX',null,null,null,null,null,null,null,null,'F',null,null,null,null,null);
  END LOOP;
END;
/

commit;


-----------------------------------------------------------------------------------------------------------------
-- Setup TPAYMENTTRANSACTIONCOLD tables
-----------------------------------------------------------------------------------------------------------------
CREATE TABLE "TPAYMENTTRANSACTIONCOLD" 
   (	"PAYMENTTRANSACTIONKEY" NUMBER(38,0), 
	"DISPLAYTRANSACTIONID" VARCHAR2(128 CHAR), 
	"STATUS" VARCHAR2(30 CHAR), 
	"DETAILS" "SYS"."XMLTYPE" , 
	"PROCESSINGDETAILS" "SYS"."XMLTYPE" , 
	"BANKKEY" NUMBER(38,0), 
	"BANKGROUPID" VARCHAR2(30 CHAR), 
	"OUTGINTCHGCLEARINGCNDTNKEY" NUMBER(38,0), 
	"OPICKEY" NUMBER(38,0), 
	"OUTGINSTRBUSINESSPRTCPNTKEY" NUMBER(38,0), 
	"OUTGINSTRSETTLEMENTPRTCPNTKEY" NUMBER(38,0), 
	"INCOMINGINSTRUCTIONKEY" NUMBER(38,0), 
	"CANCELRECONCILIATIONKEY" NUMBER(38,0), 
	"REJECTRECONCILIATIONKEY" NUMBER(38,0), 
	"INCOMINGTRANSACTIONGROUPKEY" NUMBER(38,0), 
	"OUTGOINGTRANSACTIONGROUPKEY" NUMBER(38,0), 
	"BANKPAYMENTTYPEKEY" NUMBER(38,0), 
	"BANKINGACCOUNTKEY" NUMBER(38,0), 
	"RECEIVINGENTITYKEY" NUMBER(38,0), 
	"VERSION" NUMBER(38,0), 
	"WHENMODIFIED" DATE, 
	"CLASSIFICATIONIDX" VARCHAR2(256 CHAR), 
	"ENDTOENDIDIDX" VARCHAR2(256 CHAR), 
	"FIRSTINSTRUCTINGAGENTTRNIDIDX" VARCHAR2(256 CHAR), 
	"SETTLEMENTAMOUNTIDX" NUMBER(38,5), 
	"SETTLEMENTCURRENCYIDX" VARCHAR2(256 CHAR), 
	"INCOMINGSETTLEMENTDAYIDX" VARCHAR2(10 CHAR), 
	"SETTLEMENTDAYIDX" VARCHAR2(10 CHAR), 
	"DEBITCREDITINDICATORIDX" CHAR(1 CHAR), 
	"PROCESSINGSCHEMEIDX" VARCHAR2(256 CHAR), 
	"INSTRUCTEDDAYIDX" VARCHAR2(10 CHAR), 
	"RTRANSACTIONQUALIFICATIONIDX" VARCHAR2(256 CHAR), 
	"ORIGINALENDTOENDIDIDX" VARCHAR2(256 CHAR), 
	"PRIORITYIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYNAMEIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYACCOUNTIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYAGENTIDIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYAGENT2IDIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYAGENT3IDIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYAGENT4IDIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYAGENT5IDIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYNAMEIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYACCOUNTIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYAGENTIDIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYAGENT2IDIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYAGENT3IDIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYAGENT4IDIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYAGENT5IDIDX" VARCHAR2(256 CHAR), 
	"PROCESSINGDAYIDX" VARCHAR2(10 CHAR), 
	"INCOMINGSETTLEMENTAMOUNTIDX" NUMBER(38,5), 
	"INCOMINGSETTLEMENTCURRENCYIDX" VARCHAR2(256 CHAR), 
	"ATTACHMENTCOLLECTIONIDIDX" NUMBER(38,0), 
	"ONUSFLAGIPX" CHAR(1 CHAR), 
	"DUPLICATECHECKHASHIPX" VARCHAR2(256 CHAR), 
	"UNROUTABLEFROMINSTRUCTIONIPX" CHAR(1 CHAR), 
	"OUTBOUNDIPX" CHAR(1 CHAR), 
	"OMITTEDFLAGIPX" CHAR(1 CHAR), 
	"RISKFILTERCHECKTIMESTAMPIPX" DATE,
  "ILMKEY" TIMESTAMP default SYSTIMESTAMP NOT NULL
   ) 
  XMLTYPE COLUMN DETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_COLD_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
  XMLTYPE COLUMN PROCESSINGDETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_COLD_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
  TABLESPACE "ILM_COLD_TBS"
  PARTITION BY RANGE (ILMKEY) 
  SUBPARTITION BY HASH(PAYMENTTRANSACTIONKEY) SUBPARTITIONS 16
  (
      PARTITION P9999_12 VALUES LESS THAN (MAXVALUE)
  );

-- add index
CREATE INDEX "I_TXNc_STATUS" ON "TPAYMENTTRANSACTIONCOLD" ("STATUS")  TABLESPACE "ILM_COLD_TBS";
CREATE INDEX "I_TXNc_OPIC" ON "TPAYMENTTRANSACTIONCOLD" ("OPICKEY")  TABLESPACE "ILM_COLD_TBS";
CREATE INDEX "I_TXNc_INSTRUCTION" ON "TPAYMENTTRANSACTIONCOLD" ("INCOMINGINSTRUCTIONKEY") TABLESPACE "ILM_COLD_TBS";
CREATE INDEX "I_TXNc_SETTLEMENTDAYIDX" ON "TPAYMENTTRANSACTIONCOLD" ("SETTLEMENTAMOUNTIDX") TABLESPACE "ILM_COLD_TBS" ;
CREATE INDEX "I_TXNc_INCSETTLMTDAY" ON "TPAYMENTTRANSACTIONCOLD" ("INCOMINGSETTLEMENTDAYIDX") TABLESPACE "ILM_COLD_TBS" ;
CREATE INDEX "I_TXNc_ENDTOENDID" ON "TPAYMENTTRANSACTIONCOLD" ("BANKKEY", "ENDTOENDIDIDX") TABLESPACE "ILM_COLD_TBS" ;
CREATE INDEX "I_TXNc_CREDITPARTYACCOUNTIDX" ON "TPAYMENTTRANSACTIONCOLD" (UPPER("CREDITPARTYACCOUNTIDX")) TABLESPACE "ILM_COLD_TBS" ;
CREATE INDEX "I_TXNc_DEBITPARTYACCOUNTIDX" ON "TPAYMENTTRANSACTIONCOLD" (UPPER("DEBITPARTYACCOUNTIDX")) TABLESPACE "ILM_COLD_TBS" ;

-- add constraint
ALTER TABLE "TPAYMENTTRANSACTIONCOLD" ADD CONSTRAINT "U_PAYMENTTRANSACTIONc" UNIQUE ("DISPLAYTRANSACTIONID")
  USING INDEX (CREATE UNIQUE INDEX "U_TRNcDISPLAYID" ON "TPAYMENTTRANSACTIONCOLD" ("DISPLAYTRANSACTIONID") TABLESPACE "ILM_COLD_TBS" )  ENABLE;

ALTER TABLE "TPAYMENTTRANSACTIONCOLD" ADD CONSTRAINT "PK_PAYMENTTRANSACTIONc" PRIMARY KEY ("PAYMENTTRANSACTIONKEY") ENABLE;

-- add not null constraints
ALTER TABLE "TPAYMENTTRANSACTIONCOLD" MODIFY ("WHENMODIFIED" NOT NULL ENABLE);
ALTER TABLE "TPAYMENTTRANSACTIONCOLD" MODIFY ("VERSION" NOT NULL ENABLE);
ALTER TABLE "TPAYMENTTRANSACTIONCOLD" MODIFY ("BANKGROUPID" NOT NULL ENABLE);
ALTER TABLE "TPAYMENTTRANSACTIONCOLD" MODIFY ("BANKKEY" NOT NULL ENABLE);
ALTER TABLE "TPAYMENTTRANSACTIONCOLD" MODIFY ("DISPLAYTRANSACTIONID" NOT NULL ENABLE);
ALTER TABLE "TPAYMENTTRANSACTIONCOLD" MODIFY ("PAYMENTTRANSACTIONKEY" NOT NULL ENABLE);


-----------------------------------------------------------------------------------------------------------------
-- Setup TPAYMENTINTERCHANGETEMP tables
-----------------------------------------------------------------------------------------------------------------
-- create temp table
CREATE TABLE TPAYMENTTRANSACTIONTEMP
(	"PAYMENTTRANSACTIONKEY" NUMBER(38,0), 
	"DISPLAYTRANSACTIONID" VARCHAR2(128 CHAR), 
	"STATUS" VARCHAR2(30 CHAR), 
	"DETAILS" "SYS"."XMLTYPE" , 
	"PROCESSINGDETAILS" "SYS"."XMLTYPE" , 
	"BANKKEY" NUMBER(38,0), 
	"BANKGROUPID" VARCHAR2(30 CHAR), 
	"OUTGINTCHGCLEARINGCNDTNKEY" NUMBER(38,0), 
	"OPICKEY" NUMBER(38,0), 
	"OUTGINSTRBUSINESSPRTCPNTKEY" NUMBER(38,0), 
	"OUTGINSTRSETTLEMENTPRTCPNTKEY" NUMBER(38,0), 
	"INCOMINGINSTRUCTIONKEY" NUMBER(38,0), 
	"CANCELRECONCILIATIONKEY" NUMBER(38,0), 
	"REJECTRECONCILIATIONKEY" NUMBER(38,0), 
	"INCOMINGTRANSACTIONGROUPKEY" NUMBER(38,0), 
	"OUTGOINGTRANSACTIONGROUPKEY" NUMBER(38,0), 
	"BANKPAYMENTTYPEKEY" NUMBER(38,0), 
	"BANKINGACCOUNTKEY" NUMBER(38,0), 
	"RECEIVINGENTITYKEY" NUMBER(38,0), 
	"VERSION" NUMBER(38,0), 
	"WHENMODIFIED" DATE, 
	"CLASSIFICATIONIDX" VARCHAR2(256 CHAR), 
	"ENDTOENDIDIDX" VARCHAR2(256 CHAR), 
	"FIRSTINSTRUCTINGAGENTTRNIDIDX" VARCHAR2(256 CHAR), 
	"SETTLEMENTAMOUNTIDX" NUMBER(38,5), 
	"SETTLEMENTCURRENCYIDX" VARCHAR2(256 CHAR), 
	"INCOMINGSETTLEMENTDAYIDX" VARCHAR2(10 CHAR), 
	"SETTLEMENTDAYIDX" VARCHAR2(10 CHAR), 
	"DEBITCREDITINDICATORIDX" CHAR(1 CHAR), 
	"PROCESSINGSCHEMEIDX" VARCHAR2(256 CHAR), 
	"INSTRUCTEDDAYIDX" VARCHAR2(10 CHAR), 
	"RTRANSACTIONQUALIFICATIONIDX" VARCHAR2(256 CHAR), 
	"ORIGINALENDTOENDIDIDX" VARCHAR2(256 CHAR), 
	"PRIORITYIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYNAMEIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYACCOUNTIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYAGENTIDIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYAGENT2IDIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYAGENT3IDIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYAGENT4IDIDX" VARCHAR2(256 CHAR), 
	"DEBITPARTYAGENT5IDIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYNAMEIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYACCOUNTIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYAGENTIDIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYAGENT2IDIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYAGENT3IDIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYAGENT4IDIDX" VARCHAR2(256 CHAR), 
	"CREDITPARTYAGENT5IDIDX" VARCHAR2(256 CHAR), 
	"PROCESSINGDAYIDX" VARCHAR2(10 CHAR), 
	"INCOMINGSETTLEMENTAMOUNTIDX" NUMBER(38,5), 
	"INCOMINGSETTLEMENTCURRENCYIDX" VARCHAR2(256 CHAR), 
	"ATTACHMENTCOLLECTIONIDIDX" NUMBER(38,0), 
	"ONUSFLAGIPX" CHAR(1 CHAR), 
	"DUPLICATECHECKHASHIPX" VARCHAR2(256 CHAR), 
	"UNROUTABLEFROMINSTRUCTIONIPX" CHAR(1 CHAR), 
	"OUTBOUNDIPX" CHAR(1 CHAR), 
	"OMITTEDFLAGIPX" CHAR(1 CHAR), 
	"RISKFILTERCHECKTIMESTAMPIPX" DATE,
  "ILMKEY" TIMESTAMP default SYSTIMESTAMP NOT NULL)
  XMLTYPE COLUMN DETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_COLD_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
  XMLTYPE COLUMN PROCESSINGDETAILS STORE AS SECUREFILE CLOB (TABLESPACE ILM_COLD_TBS ENABLE STORAGE IN ROW COMPRESS LOW CACHE)
  TABLESPACE "ILM_COLD_TBS"  
  PARTITION BY HASH(PAYMENTTRANSACTIONKEY) PARTITIONS 16;


-- add constraint
ALTER TABLE "TPAYMENTTRANSACTIONTEMP" ADD CONSTRAINT "U_PAYMENTTRANSACTIONt" UNIQUE ("DISPLAYTRANSACTIONID")
  USING INDEX (CREATE UNIQUE INDEX "U_TRNtDISPLAYID" ON "TPAYMENTTRANSACTIONTEMP" ("DISPLAYTRANSACTIONID") TABLESPACE "ILM_COLD_TBS" )  ENABLE;

ALTER TABLE "TPAYMENTTRANSACTIONTEMP" ADD CONSTRAINT "PK_PAYMENTTRANSACTIONt" PRIMARY KEY ("PAYMENTTRANSACTIONKEY") ENABLE;

-- add not null constraints
ALTER TABLE "TPAYMENTTRANSACTIONTEMP" MODIFY ("WHENMODIFIED" NOT NULL ENABLE);
ALTER TABLE "TPAYMENTTRANSACTIONTEMP" MODIFY ("VERSION" NOT NULL ENABLE);
ALTER TABLE "TPAYMENTTRANSACTIONTEMP" MODIFY ("BANKGROUPID" NOT NULL ENABLE);
ALTER TABLE "TPAYMENTTRANSACTIONTEMP" MODIFY ("BANKKEY" NOT NULL ENABLE);
ALTER TABLE "TPAYMENTTRANSACTIONTEMP" MODIFY ("DISPLAYTRANSACTIONID" NOT NULL ENABLE);
ALTER TABLE "TPAYMENTTRANSACTIONTEMP" MODIFY ("PAYMENTTRANSACTIONKEY" NOT NULL ENABLE);

-----------------------------------------------------------------------------------------------------------------
-- ILM tables population
-----------------------------------------------------------------------------------------------------------------
TRUNCATE TABLE ILMCONFIG;
INSERT INTO ILMCONFIG (ID, PARAM, VALUE, LASTMODIFIED) VALUES (-1, 'HOT_TABLESPACE_NAME', 'ILM_HOT_TBS', SYSTIMESTAMP);
INSERT INTO ILMCONFIG (ID, PARAM, VALUE, LASTMODIFIED) VALUES (-2, 'WARM_TABLESPACE_NAME', 'ILM_WARM_TBS', SYSTIMESTAMP);
INSERT INTO ILMCONFIG (ID, PARAM, VALUE, LASTMODIFIED) VALUES (-3, 'COLD_TABLESPACE_NAME', 'ILM_COLD_TBS', SYSTIMESTAMP);
INSERT INTO ILMCONFIG (ID, PARAM, VALUE, LASTMODIFIED) VALUES (-4, 'DORMANT_TABLESPACE_NAME', 'ILM_DORMANT_TBS', SYSTIMESTAMP);
INSERT INTO ILMCONFIG (ID, PARAM, VALUE, LASTMODIFIED) VALUES (-5, 'PARALLEL_DEGREE', '4', SYSTIMESTAMP);
INSERT INTO ILMCONFIG (ID, PARAM, VALUE, LASTMODIFIED) VALUES (-6, 'ONLINE_MOVE', 'FALSE', SYSTIMESTAMP);

TRUNCATE TABLE ILMMANAGEDTABLE;
INSERT INTO ILMMANAGEDTABLE(ID, TABLENAME, TEMPTABLENAME, COLDTABLENAME, HOTRETENTION, WARMRETENTION, COLDRETENTION, WARMCOMPRESSION, COLDCOMPRESSION, DORMANTCOMPRESSION, MOVESEQUENCE, HOTSTATUS, WARMSTATUS, COLDSTATUS, LASTMODIFIED)
VALUES (-1, 'TPAYMENTINTERCHANGE', 'TPAYMENTINTERCHANGETEMP', 'TPAYMENTINTERCHANGECOLD', 1, 1, 1, 'OLTP', 'OLTP', 'OLTP', 1, null, null, null, sysdate);

INSERT INTO ILMMANAGEDTABLE(ID, TABLENAME, TEMPTABLENAME, COLDTABLENAME, HOTRETENTION, WARMRETENTION, COLDRETENTION, WARMCOMPRESSION, COLDCOMPRESSION, DORMANTCOMPRESSION, MOVESEQUENCE, HOTSTATUS, WARMSTATUS, COLDSTATUS, LASTMODIFIED)
VALUES (-2, 'TPAYMENTTRANSACTION', 'TPAYMENTTRANSACTIONTEMP', 'TPAYMENTTRANSACTIONCOLD', 1, 1, 1, 'OLTP', 'OLTP', 'OLTP', 2, null, null, null, sysdate);
commit;
