-----------------------------------------------
-- Create ILM tables
-----------------------------------------------
CREATE TABLE "ILMJOB" (	
  "ID" NUMBER(38,0) NOT NULL, 
  "JOBNAME" VARCHAR2(50 CHAR) NOT NULL, 
  "STATUS" VARCHAR2(10 CHAR) NOT NULL, 
  "FROMTABLESPACE" VARCHAR2(30 CHAR) NOT NULL, 
  "TOTABLESPACE" VARCHAR2(30 CHAR) NOT NULL, 
  "STARTTIME" TIMESTAMP NOT NULL,
  "ENDTIME" TIMESTAMP,
  CONSTRAINT PK_ILMJOB PRIMARY KEY (ID)
);
CREATE INDEX I_ILMJOB_JOBNAME ON ILMJOB (JOBNAME);

CREATE TABLE "ILMTASK" (	
  "ID" NUMBER(38,0) NOT NULL,
  "JOBID" NUMBER(38,0) NOT NULL,
  "STEPID" VARCHAR2(100 CHAR) NOT NULL, 
  "STATUS" VARCHAR2(10 CHAR) NOT NULL, 
  "STARTTIME" TIMESTAMP NOT NULL,
  "ENDTIME" TIMESTAMP,
  CONSTRAINT PK_ILMTASK PRIMARY KEY (ID),
  CONSTRAINT FK_ILMTASK_ILMJOB FOREIGN KEY (JOBID) REFERENCES ILMJOB(ID)
);
CREATE INDEX I_ILMTASK_JOBSTEPID ON ILMTASK (JOBID, STEPID);

CREATE TABLE "ILMLOG" (	
  "ID" NUMBER(38,0) NOT NULL, 
	"MESSAGE" VARCHAR2(400 CHAR) NOT NULL, 
  "WHENCREATED" TIMESTAMP  NOT NULL,
  CONSTRAINT PK_ILMLOG PRIMARY KEY (ID)
);

CREATE TABLE "ILMMANAGEDTABLE" (	
  "ID" NUMBER(38,0) NOT NULL, 
  "TABLENAME" VARCHAR2(30 CHAR) NOT NULL, 
  "TEMPTABLENAME" VARCHAR2(30 CHAR) NOT NULL,
  "COLDTABLENAME" VARCHAR2(30 CHAR) NOT NULL, 
  "HOTRETENTION" NUMBER(3,0) NOT NULL,
  "WARMRETENTION" NUMBER(3,0) NOT NULL,
  "COLDRETENTION" NUMBER(3,0) NOT NULL,
  "WARMCOMPRESSION" VARCHAR2(30 CHAR),
  "COLDCOMPRESSION" VARCHAR2(30 CHAR),
  "DORMANTCOMPRESSION" VARCHAR2(30 CHAR),
  "MOVESEQUENCE" NUMBER(4,0) NOT NULL,
  "HOTSTATUS" VARCHAR2(15 CHAR),
  "WARMSTATUS" VARCHAR2(15 CHAR),
  "COLDSTATUS" VARCHAR2(15 CHAR),
  "LASTMODIFIED" TIMESTAMP  NOT NULL,
  CONSTRAINT PK_ILMMANAGEDTABLE PRIMARY KEY (ID),
  CONSTRAINT ILMMANAGEDTABLE_MVSEQ_UNIQ UNIQUE (MOVESEQUENCE)
);
CREATE INDEX I_ILMMANAGEDTABLE_TABLENAME ON ILMMANAGEDTABLE (TABLENAME);

CREATE TABLE "ILMCONFIG" (	
  "ID" NUMBER(38,0) NOT NULL, 
  "PARAM" VARCHAR2(30 CHAR) NOT NULL, 
	"VALUE" VARCHAR2(50 CHAR) NOT NULL, 
  "LASTMODIFIED" TIMESTAMP  NOT NULL,
  CONSTRAINT PK_ILMCONFIG PRIMARY KEY (ID)
);
CREATE INDEX I_ILMCONFIG_PARAM ON ILMCONFIG (PARAM);

-----------------------------------------------
-- Create ILM sequences
-----------------------------------------------
CREATE SEQUENCE "ILMJOB_SEQUENCE" MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE "ILMTASK_SEQUENCE" MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE "ILMLOG_SEQUENCE" MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE "ILMMANAGEDTABLE_SEQUENCE" MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
CREATE SEQUENCE "ILMCONFIG_SEQUENCE" MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
