create or replace PACKAGE ILM_CORE AS 
  -- package constant
  JOBSTATUS_STARTED CONSTANT VARCHAR2(10) := 'STARTED';
  JOBSTATUS_FAILED CONSTANT VARCHAR2(10) := 'FAILED';
  JOBSTATUS_ENDED CONSTANT VARCHAR2(10) := 'ENDED';
  
  
  TASKSTATUS_STARTED CONSTANT VARCHAR2(10) := 'STARTED';
  TASKSTATUS_FAILED CONSTANT VARCHAR2(10) := 'FAILED';
  TASKSTATUS_ENDED CONSTANT VARCHAR2(10) := 'ENDED';
  
  
  
  -- package variable
  FROM_TBS VARCHAR2(30);
  TO_TBS VARCHAR2(30);
  
  CURRENT_JOB_ID NUMBER := 0;
  CURRENT_TASK_ID NUMBER := 0;
  CURRENT_MOVE_SEQUENCE NUMBER := 0;
  CURRENT_OPERATION_ID NUMBER := 0;
  
  -- procedure 
  PROCEDURE RUN_HOT2WARM_JOB(RESUME_JOB_ID in NUMBER);
  --PROCEDURE RUN_WARM2COLD_JOB(RESUME_JOB_ID in NUMBER);
  -- PROCEDURE RUN_COLD2DORMANT_JOB(RESUME_JOB_ID in NUMBER);
  
  PROCEDURE RUN_TASK(OPERATION in VARCHAR2, OPERATION_ID in NUMBER);
  PROCEDURE MOVE_SUBPARTITION(TABLE_NAME in VARCHAR2);
  PROCEDURE LOG_MESSAGE (MESSAGE in VARCHAR2);

END ILM_CORE;