create or replace PACKAGE ILM_CORE AS 
  -----------------------------------------------------------------------------------------------------------------
  -- Package constant
  -----------------------------------------------------------------------------------------------------------------
  HOT2WARM_JOB CONSTANT VARCHAR2(15) := 'HOT2WARM';
  WARM2COLD_JOB CONSTANT VARCHAR2(15) := 'WARM2COLD';
  COLD2DORMANT_JOB CONSTANT VARCHAR2(15) := 'COLD2DORMANT';
  HOT2COLD_JOB CONSTANT VARCHAR2(15) := 'HOT2COLD';
  
  HOT_STAGE CONSTANT VARCHAR2(10) := 'HOT';
  WARM_STAGE CONSTANT VARCHAR2(10) := 'WARM';
  COLD_STAGE CONSTANT VARCHAR2(10) := 'COLD';
  DORMANT_STAGE CONSTANT VARCHAR2(10) := 'DORMANT';
  
  JOBSTATUS_STARTED CONSTANT VARCHAR2(10) := 'STARTED';
  JOBSTATUS_FAILED CONSTANT VARCHAR2(10) := 'FAILED';
  JOBSTATUS_ENDED CONSTANT VARCHAR2(10) := 'ENDED';
  
  TASKSTATUS_STARTED CONSTANT VARCHAR2(10) := 'STARTED';
  TASKSTATUS_FAILED CONSTANT VARCHAR2(10) := 'FAILED';
  TASKSTATUS_ENDED CONSTANT VARCHAR2(10) := 'ENDED';
  
  ILMTABLESTATUS_VALID CONSTANT VARCHAR2(15) := 'VALID';
  ILMTABLESTATUS_PARTITIONMOVE CONSTANT VARCHAR2(15) := 'PARTITION_MOVE';
  ILMTABLESTATUS_INDEXREBUILD CONSTANT VARCHAR2(15) := 'INDEX_REBUILD';
  ILMTABLESTATUS_LOBMOVE CONSTANT VARCHAR2(15) := 'LOB_MOVE';
  
  COMPRESSION_NONE CONSTANT VARCHAR2(30) := 'NONE';
  COMPRESSION_BASIC CONSTANT VARCHAR2(30) := 'BASIC';
  COMPRESSION_OLTP CONSTANT VARCHAR2(30) := 'OLTP';
  COMPRESSION_WAREHOUSE_LOW CONSTANT VARCHAR2(30) := 'WAREHOUSE_LOW';
  COMPRESSION_WAREHOUSE_HIGH CONSTANT VARCHAR2(30) := 'WAREHOUSE_HIGH';
  COMPRESSION_ARCHIVE_LOW CONSTANT VARCHAR2(30) := 'ARCHIVE_LOW';
  COMPRESSION_ARCHIVE_HIGH CONSTANT VARCHAR2(30) := 'ARCHIVE_HIGH';
  
  -----------------------------------------------------------------------------------------------------------------
  -- Package variable
  -----------------------------------------------------------------------------------------------------------------
  FROM_STAGE VARCHAR2(10);
  TO_STAGE VARCHAR2(10);
  
  FROM_TBS VARCHAR2(30);
  TO_TBS VARCHAR2(30);
  
  CURRENT_JOB_ID NUMBER;
  CURRENT_TASK_ID NUMBER;
  CURRENT_MOVE_SEQUENCE NUMBER;
  CURRENT_OPERATION_ID NUMBER;
  
  JOB_START_TSP TIMESTAMP := SYSTIMESTAMP;
  TEXT_BUFFER VARCHAR2(200);
  
  -----------------------------------------------------------------------------------------------------------------
  -- Procedures 
  -----------------------------------------------------------------------------------------------------------------
  -- flow
  PROCEDURE RUN_HOT2WARM_JOB;
  PROCEDURE RUN_WARM2COLD_JOB;
  PROCEDURE RUN_JOB(I_JOB VARCHAR2, I_RESUME_JOB_ID in NUMBER DEFAULT NULL);
  PROCEDURE RUN_TASK(OPERATION in VARCHAR2, CURRENT_STEP_ID in VARCHAR2);
  PROCEDURE LOG_MESSAGE (I_MESSAGE in VARCHAR2);
  PROCEDURE THROW_EXCEPTION (ERROR_MESSAGE in VARCHAR2);
  
  -- data 
  PROCEDURE MOVE_SUBPARTITION(I_TABLE_NAME in VARCHAR2, I_PARTITION_NAME in VARCHAR2);
  PROCEDURE MODIFY_PARTITION_TBS(I_TABLE_NAME in VARCHAR2, I_PARTITION_NAME in VARCHAR2, I_TO_TBS in VARCHAR2); 
  PROCEDURE EXCHANGE_PARTITION(I_PARTITION_TABLE_NAME in VARCHAR2, I_PARTITION_NAME in VARCHAR2, I_TABLE_NAME in VARCHAR2);
  PROCEDURE CREATE_PARTITION(I_TABLE_NAME in VARCHAR2, I_PARTITION_NAME in VARCHAR2, I_HIGH_VALUE in TIMESTAMP);
  PROCEDURE DROP_PARTITION(I_TABLE_NAME in VARCHAR2, I_PARTITION_NAME in VARCHAR2);
  
  -- lob
  PROCEDURE MOVE_SUBPARTITIONED_LOB(I_TABLE_NAME in VARCHAR2, I_PARTITION_NAME in VARCHAR2, I_FROM_TBS in VARCHAR2, I_TO_TBS in VARCHAR2);
  
  -- index
  PROCEDURE REBUILD_GLOBAL_INDEX(I_TABLE_NAME in VARCHAR2);
  PROCEDURE REBUILD_SUBPART_INDEX(I_TABLE_NAME in VARCHAR2, I_PARTITION_NAME in VARCHAR2);
  PROCEDURE MOVE_SUBPART_INDEX(I_TABLE_NAME in VARCHAR2, I_PARTITION_NAME in VARCHAR2, I_FROM_TBS in VARCHAR2, I_TO_TBS in VARCHAR2);
  PROCEDURE MODIFY_PARTITION_INDEX_TBS(I_TABLE_NAME in VARCHAR2, I_PARTITION_NAME in VARCHAR2, I_TO_TBS in VARCHAR2);
  
  -----------------------------------------------------------------------------------------------------------------
  -- Functions
  -----------------------------------------------------------------------------------------------------------------

END ILM_CORE;