create or replace PACKAGE ILM_COMMON AS 

  FUNCTION TABLESPACE_EXIST(TBS_NAME in VARCHAR2) RETURN NUMBER;
  FUNCTION CAN_RESUME_JOB(JOB_ID in NUMBER) RETURN NUMBER;
  FUNCTION GET_RETENTION(TABLE_NAME in VARCHAR2, STAGE in VARCHAR2) RETURN NUMBER;
END ILM_COMMON;